Create schema and models
delta/aor-backend pull request #10
Opened 2021-12-23 18:05 UTC by Guruprasanna02

Closes #2

2021-12-24 15:59 UTC, TejusR commented on src/models.rs
> +
Shouldn't you also add another struct for inserting a new record?

2021-12-26 14:00 UTC, sakthi-prasath submitted a review, later dismissed

2021-12-26 15:03 UTC, pradeep-707 requested changes

2021-12-26 15:03 UTC, pradeep-707 commented on migrations/2021-12-23-175733_AOT/up.sql
> +	email VARCHAR(255) NOT NULL,
make email unique

2021-12-26 15:03 UTC, pradeep-707 commented on migrations/2021-12-23-175733_AOT/up.sql
> +	attack_Score INTEGER NOT NULL,
s should be small

2021-12-26 15:03 UTC, pradeep-707 commented on migrations/2021-12-23-175733_AOT/up.sql
> +	start_date serial NOT NULL,
use date type

2021-12-26 15:03 UTC, pradeep-707 commented on migrations/2021-12-23-175733_AOT/up.sql
> +	pathlist VARCHAR(255) NOT NULL,
255 might not be enough, make it 1000

2021-12-29 07:00 UTC, pradeep-707 approved these changes

2021-12-29 07:03 UTC, merged