Feat: Add Google OAuth 2.0
delta/aor-backend pull request #64
Opened 2024-01-12 05:03 UTC by itsKhadeer

added google oauth 2.0
added Jwt Authorization with custom extractor

2024-01-16 09:14 UTC, novice0192 requested changes

2024-01-16 09:14 UTC, novice0192 commented on .env.example
> +JWT_SECRET=
This and cookie key seems same, if they serve the same purpose have only one

2024-01-16 09:14 UTC, novice0192 commented on .env.example
> +JWT_MAX_AGE=
Session duration is also defined in main.rs, check it out once and have only this or only that to avoid any possible conflict

2024-01-16 09:14 UTC, novice0192 commented on src/api/auth/mod.rs
Remove regular (non pragyan auth) from login function... it is not of use with oauth

2024-01-16 09:14 UTC, novice0192 commented on src/api/auth/util.rs
> +            is_pragyan: &true,
is_pragyan should be false

2024-01-17 09:07 UTC, itsKhadeer commented on .env.example
> +JWT_MAX_AGE=
the max age of the cookie should be same as the max age of the jwt, so now there is a common "MAX_AGE" variable in the env.example

2024-01-17 09:07 UTC, itsKhadeer commented on src/api/auth/mod.rs
Done

2024-01-17 09:09 UTC, itsKhadeer commented on .env.example
> +JWT_SECRET=
No, jwt needs a seperate secret as far as I know, its more security

2024-01-17 09:10 UTC, itsKhadeer commented on src/api/auth/util.rs
> +            is_pragyan: &true,
done

2024-01-17 12:34 UTC, novice0192 commented on src/api/auth/util.rs
> +            is_pragyan: &true,
It still shows true...

2024-01-23 14:52 UTC, itsKhadeer commented on src/api/auth/util.rs
> +            is_pragyan: &true,
done

2024-01-26 13:09 UTC, itsKhadeer commented on .env.example
> +JWT_SECRET=
changed

2024-01-27 18:14 UTC, novice0192 approved these changes

2024-01-27 18:16 UTC, merged